---
apiVersion: v1
kind: Service
metadata:
  name: srv-web
  labels:
    project: k8s-app
    app: web-service
    tier: frontend
    role: web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-service
