apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
spec:
  type: ClusterIP
  selector:
    component: elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      project: k8s-app
      app: elasticsearch
      role: database
      tier: backend
  replicas: 3
  serviceName: elasticsearch
  template:
    metadata:
      labels:
        project: k8s-app
        app: elasticsearch
        role: database
        tier: backend
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: rolindroy/elasticsearch:6.5.4
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
        command: [ "/usr/share/elasticsearch/bin/elasticsearch" ]
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
        env:
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx512m
        - name: bootstrap.memory_lock
          value: "true"
        ports:
        - containerPort: 9200
          name: rest-port
        - containerPort: 9300
          name: node-port
        volumeMounts:
        - mountPath: /usr/share/elasticsearch
          name: storage
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: gp2
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 1Gi
